# frozen_string_literal: true

require_relative 'zuql/version'
require_relative 'zuql/errors'
require_relative 'zuql/types'
require_relative 'zuql/contracts'
require_relative 'zuql/domain_support_registry'
require_relative 'zuql/metadata_audit'
require_relative 'zuql/query_prompt'
require_relative 'zuql/providers/fixture_provider'
require_relative 'zuql/providers/openai_provider'
require_relative 'zuql/semantic_registry'
require_relative 'zuql/metadata_retriever'
require_relative 'zuql/natural_language_interpreter'
require_relative 'zuql/relationship_graph'
require_relative 'zuql/semantic_resolver'
require_relative 'zuql/filter_compatibility_validator'
require_relative 'zuql/plan_projection'
require_relative 'zuql/grain_validator'
require_relative 'zuql/query_planner'
require_relative 'zuql/data_query_registry'
require_relative 'zuql/data_query_literal'
require_relative 'zuql/data_query_identifier'
require_relative 'zuql/data_query_order'
require_relative 'zuql/data_query_selection_validator'
require_relative 'zuql/data_query_filter_validator'
require_relative 'zuql/data_query_compiler'
require_relative 'zuql/sql_safety_validator'
require_relative 'zuql/query_explainer'
require_relative 'zuql/pipeline'
require_relative 'zuql/renderers/result_input'
require_relative 'zuql/renderers/terminal_renderer'
require_relative 'zuql/renderers/json_renderer'
require_relative 'zuql/renderers/markdown_renderer'
require_relative 'zuql/exclusive_file_writer'
require_relative 'zuql/cli'

# Natural-language-to-SQL domain foundation for Zuora.
module ZuQL
end
